version: 1.0
desc: multihead-v4-global-effnetv2s
train:
  parquet_path: data/global/0032836-250426092105405_processing_metadata_postprocessed_quality_filtered.parquet
  img_dir: data/global/images
  out_dir: data/global/models
  fold: '1'
  min_img_per_spc: 50
  model_name: multihead-v4-global-effnetv2s
  model_arch_name: efficientnet_v2_s
  nb_epochs: 5
  base_lr: 0.001
  batch_size: 64
  aug_img_size: 460
  img_size: 256
  hierarchy_path: null
  family_filter: []
  fp16: true
  grad_clip: 1.0
  schedule: flat_cos
