name = "lepinet-H3tax-eval"
replicas = 1
[application]
name = "pytorch-te"
version = "26.05"
[product]
id = "gpu-nvidia-b200-1-gpu"
category = "gpu-nvidia-b200"
provider = "ucloud"
[time_allocation]
hours = 4
[sync]
local = ".."
remote = "/12347837/repos/lepinet"
[setup]
script = "setup-lepinet.sh"
run = "lepinet test --model '/work/lepinet/data/ucloud_models/*-lepinet-H3-taxneg1024-effnetv2s-ucloud/*.pt' --parquet /work/global_lepi/0032836-250426092105405_processing_metadata_postprocessed_quality_filtered.parquet --img-dir /work/global_lepi/images --out-dir /work/lepinet/data/ucloud_preds/H3tax-eval --test-set 0 --min-img-per-spc 0 --img-size 256 --aug-img-size 460 --batch-size 128 --num-workers 32 --eval-levels speciesKey,genusKey,familyKey"
[schedule]
auto_extend = "1h"
max_time = "10h"
[[resources]]
type = "file"
path = "/12347837/datasets/global_lepi"
read_only = true
